---
- hosts: localhost
  vars:
    xrdp_version: 0.9.2
    xorgxrdp_version: 0.2.3
    pulseaudio_version: 8.0
  tasks:

  - name: More cleanup
    become: true
    apt:
      autoremove: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Install basic tools
    become: true
    apt: name={{item}} state=present
    with_items:
      - git
      - nasm
      - bison
      - flex
      - autoconf
      - libtool
      - pkg-config
      - make
      - fakeroot
    when: ansible_distribution == 'Ubuntu'

  - name: Install basic tools
    become: true
    yum: name={{item}} state=present
    with_items:
      - git
      - nasm
      - bison
      - flex
      - autoconf
      - libtool
      - make
      - fakeroot
    when: ansible_distribution == 'CentOS'

  - name: build dependencies for  development libraries
    become: true
    apt: name={{item}} state=build-dep
    with_items:
      - libx11-dev
      - dpkg-dev
      - libavformat-dev
      - libxml2-dev
      - libfuse-dev
      - libopus-dev
      - libmp3lame-dev
      - libfl-dev
      - libxml2-dev
      - libxrandr-dev
      - libssl-dev
      - libpam0g-dev
      - libxfixes-dev
      - libjpeg-dev
      - xutils-dev
      - libpulse-dev
      - xserver-xorg-dev
      - pulseaudio
    when: ansible_distribution == 'Ubuntu'

  - name: build dependencies for  development libraries
    become: true
    yum: name={{item}} state=present
    with_items:
      - libX11-devel
      - dpkg-devel
      - libavc1394-devel
      - libxml2-devel
      - openssl-devel
      - fuse-devel
      - opus-devel
      - lame-libs
      - lame-devel
      - libfli-devel
      - libxml2-devel
      - libXrandr-devel
      - openssl-libs
      - pam-devel
      - libXfixes-devel
      - libjpeg-devel
      - pulseaudio-libs-devel
      - xorg-x11-server-devel
      - libtool-ltdl-devel
      - json-c-devel
      - libsndfile-devel
      - dbus-devel
      - speex-devel
      - libgudev1-devel
      - glib-devel
      - pulseaudio
    when: ansible_distribution == 'CentOS'

  - name: Install development libraries
    become: true
    apt: name={{item}} state=present
    with_items:
      - libx11-dev
      - libavformat-dev
      - libxml2-dev
      - libfuse-dev
      - libopus-dev
      - libmp3lame-dev
      - libfl-dev
      - libxml2-dev
      - libxrandr-dev
      - libssl-dev
      - libpam0g-dev
      - libxfixes-dev
      - libjpeg-dev
      - xutils-dev
      - libpulse-dev
      - xserver-xorg-dev
    when: ansible_distribution == 'Ubuntu'

  - name: Install everything else
    become: true
    apt: name={{item}} state=present
    with_items:
      - intltool
      - xsltproc
      - python-libxml2
      - xutils
      - xfce4
    when: ansible_distribution == 'Ubuntu'

  - name: Install everything else
    become: true
    yum: name={{item}} state=present
    with_items:
      - intltool
      - libxslt
    when: ansible_distribution == 'CentOS'

  - name: Fix dixfont.h
    become: true
    lineinfile:
      path: /usr/include/xorg/dixfont.h
      line: '#include <X11/fonts/fontutil.h>'
      state: absent

  - name: Get pulseaudio source
    shell: cd /tmp && apt-get source -y pulseaudio
    when: ansible_distribution == 'Ubuntu'

  - name: Get pulseaudio source
    get_url:
      url: https://freedesktop.org/software/pulseaudio/releases/pulseaudio-6.0.tar.gz
      dest: /tmp
    when: ansible_distribution == 'CentOS'

  - name: Unzip pulseaudio
    unarchive:
      src: /tmp/pulseaudio-6.0.tar.gz
      dest: /tmp/
    when: ansible_distribution == 'CentOS'

  - name: Download xrdp
    get_url:
      url: https://github.com/neutrinolabs/xrdp/releases/download/v{{xrdp_version}}/xrdp-{{xrdp_version}}.tar.gz
      dest: /tmp/xrdp.tar.gz

  - name: Unzip xrdp source
    unarchive:
      src: /tmp/xrdp.tar.gz
      dest: /tmp/

  - name: Download Xorgxrdp
    get_url:
      url: https://github.com/neutrinolabs/xorgxrdp/releases/download/v{{xorgxrdp_version}}/xorgxrdp-{{xorgxrdp_version}}.tar.gz
      dest: /tmp/xorgxrdp.tar.gz

  - name: Unzip xorgxrdp source
    unarchive:
      src: /tmp/xorgxrdp.tar.gz
      dest: /tmp/

  - name: Bootstrap xrdp
    shell: cd /tmp/xrdp-{{xrdp_version}}/ && ./bootstrap

  - name: Configure xrdp
    shell: cd /tmp/xrdp-{{xrdp_version}}/ && ./configure --enable-nutrinordp --enable-jpeg  --enable-fuse  --enable-opus --enable-mp3lame --enable-pixman --enable-painter --enable-rfxcodec --enable-load_pulse_modules --disable-ipv6

  - name: Make clean xrdp
    make:
      chdir: /tmp/xrdp-{{xrdp_version}}/
      target: clean

  - name: Make xrdp
    make:
      chdir: /tmp/xrdp-{{xrdp_version}}/

  - name: Make install xrdp
    become: true
    make:
      chdir: /tmp/xrdp-{{xrdp_version}}/
      target: install

  - name: Bootstrap xorgxrdp
    shell: cd /tmp/xorgxrdp-{{xorgxrdp_version}} && ./bootstrap

  - name: Configure xorgxrdp
    shell: cd /tmp/xorgxrdp-{{xorgxrdp_version}} && ./configure
    when: ansible_distribution == 'Ubuntu'

  - name: Configure xorgxrdp
    shell: 'cd /tmp/xorgxrdp-{{xorgxrdp_version}} && ./configure XRDP_CFLAGS=-I/tmp/xrdp-{{xrdp_version}}/common XRDP_LIBS=" "'
    when: ansible_distribution == 'CentOS'

  - name: Make xorgxrdp
    make:
      chdir: /tmp/xorgxrdp-{{xorgxrdp_version}}/

  - name: Make install xorgxrdp
    become: true
    make:
      chdir: /tmp/xorgxrdp-{{xorgxrdp_version}}
      target: install

  - name: Get users list
    shell: ls -1 /home
    register: home_dir

  - name: Delete noah
    become: true
    file:
      path: /home/noah
      state: absent

  - name: Add line to .xsession file
    become: true
    lineinfile:
      create: yes
      state: present
      line: xfce4-session
      dest: /home/{{item}}/.xsession
    with_items:
      - "{{home_dir.stdout_lines}}"

  - name: Change file owners
    become: true
    file:
      path: /home/{{item}}/.xsession
      owner: "{{item}}"
    with_items:
      - "{{home_dir.stdout_lines}}"

  - name: Restart xrdp service
    become: true
    shell: /etc/xrdp/xrdp.sh restart

  - name: Configure pulseaudio
    shell: cd /tmp/pulseaudio-{{pulseaudio_version}} && ./configure
    when: ansible_distribution == 'Ubuntu'

  - name: Configure pulseaudio
    shell: cd /tmp/pulseaudio-6.0 && ./configure --without-caps
    when: ansible_distribution == 'CentOS'

  - name: Change pulse_dir makefile
    replace:
      path: /tmp/xrdp-{{xrdp_version}}/sesman/chansrv/pulse/Makefile
      regexp: "^PULSE_DIR = /home/lk/pulseaudio-1\\.1"
      replace: "PULSE_DIR = /tmp/pulseaudio-{{pulseaudio_version}}"
    when: ansible_distribution == 'Ubuntu'

  - name: Change pulse_dir makefile
    replace:
      path: /tmp/xrdp-{{xrdp_version}}/sesman/chansrv/pulse/Makefile
      regexp: "^PULSE_DIR = /home/lk/pulseaudio-1\\.1"
      replace: "PULSE_DIR = /tmp/pulseaudio-6.0"
    when: ansible_distribution == 'CentOS'

  - name: Change CFLAGS  makefile
    replace:
      path: /tmp/xrdp-{{xrdp_version}}/sesman/chansrv/pulse/Makefile
      regexp: "^CFLAGS.*$"
      replace: "CFLAGS    = -Wall -O2 -I$(PULSE_DIR) -I$(PULSE_DIR)/src -DHAVE_CONFIG_H -fPIC -DXRDP_SOCKET_PATH=\\\"/tmp/.xrdp\\\""

  - name: Make clean pulseaudio
    make:
      chdir: /tmp/xrdp-{{xrdp_version}}/sesman/chansrv/pulse/
      target: clean

  - name: Make pulseaudio
    make:
      chdir: /tmp/xrdp-{{xrdp_version}}/sesman/chansrv/pulse/

  - name: Copy modules
    become: true
    copy:
      src: "{{item}}"
      dest: /usr/lib/pulse-{{pulseaudio_version}}/modules/.
    with_fileglob:
      - "/tmp/xrdp-{{xrdp_version}}/sesman/chansrv/pulse/*.so"
    when: ansible_distribution == 'Ubuntu'

  - name: Copy modules
    become: true
    copy:
      src: "{{item}}"
      dest: /usr/lib64/pulse-6.0/modules/.
    with_fileglob:
      - "/tmp/xrdp-{{xrdp_version}}/sesman/chansrv/pulse/*.so"
    when: ansible_distribution == 'CentOS'

  - name: Link xrdp
    become: true
    file:
      src: /usr/local/sbin/xrdp
      path: /usr/sbin/xrdp
      state: link

  - name: Link xrdp-sesman
    become: true
    file:
      src: /usr/local/sbin/xrdp-sesman
      path: /usr/sbin/xrdp-sesman
      state: link

  - name: Link xrdp-chansrv
    become: true
    file:
      src: /usr/local/sbin/xrdp-chansrv
      path: /usr/sbin/xrdp-chansrv
      state: link

  - name: Enable xrdp.service
    become: true
    shell: systemctl enable xrdp.service

  - name: Restart xrdp service
    become: true
    shell: /etc/xrdp/xrdp.sh restart
